env          = "dev"
aws_region   = "eu-central-1"
vpc_name     = "vpc"
vpc_cidr     = "10.0.0.0/16"
cluster_name = "eks"
availability_zone_a = "eu-central-1a"
availability_zone_b = "eu-central-1b"
availability_zone_c = "eu-central-1c"